### ISSUE TITLE
IP address value is not coming correctly

### ISSUE THREAD

**Issue by dev-build-debug** [bhargav-rathod/Logging-Utility#10]
Using Version 2.0.0, IP address value is not correctly logged. It is logging System.Net.IPHostEntry instead of machine IP on which application is running.
The string which is printing: `{"ip_address":"System.Net.IPHostEntry"}`

Sample log:
`{{"host_name": "tslajsysdev001"}, {"user_name": "ad\rpa.dev"}, {"ip_address":"System.Net.IPHostEntry"}, {"date_time":"04-May-22 11:34:03 AM"}, {"message":"04-May-22 11:34:02 AM : Main Method Started"}}`

**Comment by bhargav-rathod** [comment]
IP Address string: `\"ip_address\":\"" + System.Net.Dns.GetHostByName(System.Net.Dns.GetHostName()).AddressList[0].ToString() + "\"` will print correct value of IP Adress.

Solution for this is to replace `System.Net.Dns.GetHostByName(System.Net.Dns.GetHostName())` to `System.Net.Dns.GetHostByName(System.Net.Dns.GetHostName()).AddressList[0].ToString()`

**Comment by bhargav-rathod** [comment]
Apply Patch: #15 on 2.0.0 to fix this issue.

**Comment by dev-build-debug** [comment]
Where to download this patch? How to apply?

**Comment by dev-build-debug** [comment]
Please provide documentation for this as well for how to apply #15 on version 2.0.0.

**Comment by bhargav-rathod** [comment]
Released with patch #2.1.
Refer #15 for more details.

**Comment by dev-build-debug** [comment]
Applied patch #2.1 on Version 2.0.0 (#15) and it is working fine, printing correct IP address values for each cluster nodes.
