### ISSUE TITLE
Patch #2.1

### ISSUE THREAD

**Issue by bhargav-rathod** [bhargav-rathod/Logging-Utility#15]
This patch will contain IP Address bug fix on Version 2.0.0.

**Comment by dev-build-debug** [comment]
@bhargav-rathod - please let us know from where to download this patch as this is not present in the master branch yet.

**Comment by bhargav-rathod** [comment]
Patch #2.1 is released. Found at [here](https://github.com/bhargav-rathod/Logging-Utility/blob/master/Patch_%232.1.zip).

If below link is not working try using: https://github.com/bhargav-rathod/Logging-Utility/blob/master/Patch_%232.1.zip
